[package]
name = "lambdashell"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
libpse = { path = "../libpse" }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
